#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from datetime import datetime
import pandas as pd

try:
    import yaml
except Exception:
    yaml = None


def now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def load_config(path: str | Path) -> dict:
    if yaml is None:
        raise RuntimeError("PyYAML is required. Please install pyyaml.")
    p = Path(path)
    return yaml.safe_load(p.read_text(encoding="utf-8"))


def mkdir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def save_json(path: Path, obj) -> None:
    mkdir(path.parent)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")


def get_paths(cfg: dict) -> dict:
    project_root = Path(cfg["project_root"])
    batch_name = cfg["batch_name"]
    adaptive_root = Path(cfg["adaptive_batch_root"]) / batch_name
    reliability_root = Path(cfg["reliability_out_root"]) / batch_name
    pipeline_dir = Path(cfg["pipeline_dir"])
    pipeline_config = Path(cfg["pipeline_config"])
    mkdir(reliability_root)
    return {
        "project_root": project_root,
        "batch_name": batch_name,
        "adaptive_root": adaptive_root,
        "reliability_root": reliability_root,
        "pipeline_dir": pipeline_dir,
        "pipeline_config": pipeline_config,
    }


def read_status_table(cfg: dict) -> pd.DataFrame:
    paths = get_paths(cfg)
    standard_csv = paths["adaptive_root"] / "master_status_standard.csv"
    full_csv = paths["adaptive_root"] / "master_status.csv"
    if standard_csv.exists():
        return pd.read_csv(standard_csv)
    if full_csv.exists():
        return pd.read_csv(full_csv)
    raise FileNotFoundError(f"Missing status table: {standard_csv} or {full_csv}")


def run_command(cmd: list[str], log_file: Path, dry_run: bool) -> int:
    mkdir(log_file.parent)
    with open(log_file, "w", encoding="utf-8") as f:
        f.write(f"[TIME] {now()}\n")
        f.write("[CMD] " + " ".join(map(str, cmd)) + "\n")
        f.write(f"[DRY_RUN] {dry_run}\n\n")
        f.flush()
        if dry_run:
            return 0
        proc = subprocess.run(cmd, stdout=f, stderr=subprocess.STDOUT, text=True)
        f.write(f"\n[RETURN_CODE] {proc.returncode}\n")
        return proc.returncode


def status_filter(df: pd.DataFrame, statuses: list[str]) -> pd.DataFrame:
    if "final_case_status" not in df.columns:
        return df.iloc[0:0].copy()
    return df[df["final_case_status"].astype(str).isin(statuses)].copy()


def write_table_and_md(df: pd.DataFrame, csv_path: Path, md_path: Path, title: str, cols=None) -> None:
    mkdir(csv_path.parent)
    df.to_csv(csv_path, index=False)

    lines = [f"# {title}", "", f"- Rows: `{len(df)}`", ""]
    if len(df) == 0:
        lines.append("No records.")
    else:
        if cols:
            use_cols = [c for c in cols if c in df.columns]
            lines.append(df[use_cols].to_markdown(index=False))
        else:
            lines.append(df.to_markdown(index=False))
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def read_compact_watchlist(cfg: dict) -> pd.DataFrame:
    """Read compact watchlist generated by batch_adaptive.

    If the compact watchlist does not exist, return an empty DataFrame.
    This keeps batch_reliability compatible with older batch_adaptive outputs.
    """
    adaptive_inputs = cfg.get("adaptive_inputs", {})
    p = adaptive_inputs.get("compact_watchlist_csv", "")

    if p:
        path = Path(p)
    else:
        paths = get_paths(cfg)
        path = paths["adaptive_root"] / "batch_compact_overview" / "compact_watchlist.csv"

    if path.exists():
        return pd.read_csv(path)

    return pd.DataFrame()


def read_compact_top_routes(cfg: dict) -> pd.DataFrame:
    """Read compact top routes generated by batch_adaptive."""
    adaptive_inputs = cfg.get("adaptive_inputs", {})
    p = adaptive_inputs.get("compact_top_routes_csv", "")

    if p:
        path = Path(p)
    else:
        paths = get_paths(cfg)
        path = paths["adaptive_root"] / "batch_compact_overview" / "compact_top_routes.csv"

    if path.exists():
        return pd.read_csv(path)

    return pd.DataFrame()
