from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class RouteSpecification:
    """Canonical route specification target: method, precursor set, conditions."""

    method: str
    canonical_precursor_set: tuple[str, ...]
    temperature: float | None = None
    time: float | None = None
    atmosphere: str | None = None
    solvent: str | None = None


@dataclass(frozen=True)
class RouteReference(RouteSpecification):
    """Observed reference route with sample and split metadata."""

    sample_id: str = ""
    target_id: str | None = None
    split: str | None = None
    label_completeness: str = "unknown"


@dataclass(frozen=True)
class RouteCandidate(RouteSpecification):
    """Candidate route generated by RSP/CDG and scored by GRV."""

    sample_id: str = ""
    candidate_id: str = ""
    target_id: str | None = None
    rsp_score: float | None = None
    cdg_score: float | None = None
    legacy_grv_score: float | None = None
    grv_score: float | None = None
    rsp_rank: int | None = None
    cdg_rank: int | None = None
    final_rank: int | None = None
    candidate_provenance: tuple[str, ...] = field(default_factory=tuple)
    chemistry_features: dict[str, Any] = field(default_factory=dict)
    canonicalization_version: str = "canonicalization_v1"
    split_version: str = "iid_method_stratified_legacy"
    candidate_budget_version: str = "candidate_budget_v1"


@dataclass(frozen=True)
class CandidatePool:
    """A frozen, budgeted route candidate table."""

    pool_id: str
    split: str
    candidates: tuple[RouteCandidate, ...]
    candidate_budget_version: str = "candidate_budget_v1"
    canonicalization_version: str = "canonicalization_v1"


class RouteSkeletonProposer:
    """RSP compatibility facade for historical Stage2 components."""

    legacy_alias = "stage2"


class ConditionDistributionGenerator:
    """CDG compatibility facade for historical Stage3 components."""

    legacy_alias = "stage3"


class GlobalRouteVerifier:
    """GRV compatibility facade for historical Stage35 components."""

    legacy_alias = "stage35"

